package com.example.fittingChart;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.fittingChart.database.FittingItem;
import com.example.fittingChart.database.FittingTable;
import com.example.fittingChart.database.ShowTable;
import com.example.fittingChart.database.User;

import com.example.fittingChart.FittingItemDao;
import com.example.fittingChart.FittingTableDao;
import com.example.fittingChart.ShowTableDao;
import com.example.fittingChart.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fittingItemDaoConfig;
    private final DaoConfig fittingTableDaoConfig;
    private final DaoConfig showTableDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FittingItemDao fittingItemDao;
    private final FittingTableDao fittingTableDao;
    private final ShowTableDao showTableDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fittingItemDaoConfig = daoConfigMap.get(FittingItemDao.class).clone();
        fittingItemDaoConfig.initIdentityScope(type);

        fittingTableDaoConfig = daoConfigMap.get(FittingTableDao.class).clone();
        fittingTableDaoConfig.initIdentityScope(type);

        showTableDaoConfig = daoConfigMap.get(ShowTableDao.class).clone();
        showTableDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        fittingItemDao = new FittingItemDao(fittingItemDaoConfig, this);
        fittingTableDao = new FittingTableDao(fittingTableDaoConfig, this);
        showTableDao = new ShowTableDao(showTableDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(FittingItem.class, fittingItemDao);
        registerDao(FittingTable.class, fittingTableDao);
        registerDao(ShowTable.class, showTableDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        fittingItemDaoConfig.clearIdentityScope();
        fittingTableDaoConfig.clearIdentityScope();
        showTableDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FittingItemDao getFittingItemDao() {
        return fittingItemDao;
    }

    public FittingTableDao getFittingTableDao() {
        return fittingTableDao;
    }

    public ShowTableDao getShowTableDao() {
        return showTableDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
