package com.example.fittingChart;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.fittingChart.database.FittingTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FITTING_TABLE".
*/
public class FittingTableDao extends AbstractDao<FittingTable, String> {

    public static final String TABLENAME = "FITTING_TABLE";

    /**
     * Properties of entity FittingTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", true, "NAME");
        public final static Property DbName = new Property(1, String.class, "dbName", false, "DB_NAME");
        public final static Property Des = new Property(2, String.class, "des", false, "DES");
        public final static Property LayoutResourceID = new Property(3, Long.class, "layoutResourceID", false, "LAYOUT_RESOURCE_ID");
    }


    public FittingTableDao(DaoConfig config) {
        super(config);
    }
    
    public FittingTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FITTING_TABLE\" (" + //
                "\"NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: name
                "\"DB_NAME\" TEXT," + // 1: dbName
                "\"DES\" TEXT," + // 2: des
                "\"LAYOUT_RESOURCE_ID\" INTEGER);"); // 3: layoutResourceID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FITTING_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FittingTable entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String dbName = entity.getDbName();
        if (dbName != null) {
            stmt.bindString(2, dbName);
        }
 
        String des = entity.getDes();
        if (des != null) {
            stmt.bindString(3, des);
        }
 
        Long layoutResourceID = entity.getLayoutResourceID();
        if (layoutResourceID != null) {
            stmt.bindLong(4, layoutResourceID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FittingTable entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String dbName = entity.getDbName();
        if (dbName != null) {
            stmt.bindString(2, dbName);
        }
 
        String des = entity.getDes();
        if (des != null) {
            stmt.bindString(3, des);
        }
 
        Long layoutResourceID = entity.getLayoutResourceID();
        if (layoutResourceID != null) {
            stmt.bindLong(4, layoutResourceID);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public FittingTable readEntity(Cursor cursor, int offset) {
        FittingTable entity = new FittingTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // dbName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // des
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // layoutResourceID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FittingTable entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDbName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDes(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLayoutResourceID(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(FittingTable entity, long rowId) {
        return entity.getName();
    }
    
    @Override
    public String getKey(FittingTable entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FittingTable entity) {
        return entity.getName() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
