package com.example.fittingChart.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig fittingDataDaoConfig;
    private final DaoConfig showTableDaoConfig;

    private final UserDao userDao;
    private final FittingItemDao fittingDataDao;
    private final ShowTableDao showTableDao;


    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        fittingDataDaoConfig = daoConfigMap.get(FittingItemDao.class).clone();
        fittingDataDaoConfig.initIdentityScope(type);

        showTableDaoConfig = daoConfigMap.get(ShowTableDao.class).clone();
        showTableDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        fittingDataDao = new FittingItemDao(fittingDataDaoConfig, this);
        showTableDao = new ShowTableDao(showTableDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(FittingItem.class, fittingDataDao);
        registerDao(ShowTable.class, showTableDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        fittingDataDaoConfig.clearIdentityScope();
        showTableDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }
    public FittingItemDao getFittingDataDao() {
        return fittingDataDao;
    }
    public ShowTableDao getShowTableDao() {
        return showTableDao;
    }
}