package com.example.fittingChart.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig fittingItemDaoConfig;
    private final DaoConfig showTableDaoConfig;
    private final DaoConfig fittingTableDaoConfig;


    private final UserDao userDao;
    private final FittingItemDao fittingItemDao;
    private final ShowTableDao showTableDao;
    private final FittingTableDao fittingTableDao;



    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        fittingItemDaoConfig = daoConfigMap.get(FittingItemDao.class).clone();
        fittingItemDaoConfig.initIdentityScope(type);

        showTableDaoConfig = daoConfigMap.get(ShowTableDao.class).clone();
        showTableDaoConfig.initIdentityScope(type);

        fittingTableDaoConfig = daoConfigMap.get(FittingTableDao.class).clone();
        fittingTableDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        fittingItemDao = new FittingItemDao(fittingItemDaoConfig, this);
        showTableDao = new ShowTableDao(showTableDaoConfig, this);
        fittingTableDao = new FittingTableDao(fittingTableDaoConfig, this);


        registerDao(User.class, userDao);
        registerDao(FittingItem.class, fittingItemDao);
        registerDao(ShowTable.class, showTableDao);
        registerDao(FittingTable.class, fittingTableDao);

    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        fittingItemDaoConfig.clearIdentityScope();
        showTableDaoConfig.clearIdentityScope();
        fittingTableDaoConfig.clearIdentityScope();

    }

    public UserDao getUserDao() {
        return userDao;
    }
    public FittingItemDao getFittingItemDao() {
        return fittingItemDao;
    }
    public ShowTableDao getShowTableDao() {
        return showTableDao;
    }
    public FittingTableDao getFittingTableDao() {
        return fittingTableDao;
    }

}