package com.example.fittingChart.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCT".
*/
public class FittingTableDao extends AbstractDao<FittingTable, String> {

    public static final String TABLENAME = "FITTINGTABLE";

    /**
     * Properties of entity Product.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, Integer.class, "Name", true, "NAME");
        public final static Property DbName = new Property(1, Long.class, "DbName", false, "DBNAME");
        public final static Property Count = new Property(2, Long.class, "Count", false, "COUNT");
    }


    public ShowTableDao(DaoConfig config) {
        super(config);
    }
    
    public ShowTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHOWTABLE\" (" + //
                "\"NAME\" String PRIMARY KEY NOT NULL ," +
                "\"DBNAME\" String , " +
                "\"COUNT\" Integer);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShowTable entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        stmt.bindString(1, name);
 
        String dbName = entity.getDbName();
        stmt.bindString(2, dbName);

        Integer count = entity.getCount();
        stmt.bindLong(3, count);

    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShowTable entity) {
        stmt.clearBindings();

        String name = entity.getName();
        stmt.bindString(1, name);

        String dbName = entity.getDbName();
        stmt.bindString(2, dbName);

        Integer count = entity.getCount();
        stmt.bindLong(3, count);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ShowTable readEntity(Cursor cursor, int offset) {
        ShowTable entity = new ShowTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // Name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShowTable entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDbName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCount(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
    }
    
    @Override
    protected final String updateKeyAfterInsert(ShowTable entity, long rowId) {
        return entity.getName();
    }
    
    @Override
    public String getKey(ShowTable entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ShowTable entity) {
        return entity.getName() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}