package com.example.fittingChart.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AREA".
*/
public class UserDao extends AbstractDao<User, String> {

    public static final String TABLENAME = "AREA";

    /**
     * Properties of entity Area.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AreaCode = new Property(0, String.class, "AreaCode", true, "AREA_CODE");
        public final static Property AreaName = new Property(1, String.class, "AreaName", false, "AREA_NAME");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AREA\" (" + //
                "\"AREA_CODE\" TEXT PRIMARY KEY NOT NULL ," + // 0: AreaCode
                "\"AREA_NAME\" TEXT);"); // 1: AreaName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AREA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
//        Long Id = entity.getId();
//        if (Id != null) {
//            stmt.bindLong(1, Id);
//        }
 
        String userName = entity.getUsername();
        if (userName != null) {
            stmt.bindString(1, userName);
        }
        String slogan = entity.getSlogan();
        if (slogan != null) {
            stmt.bindString(2, slogan);
        }
        int imgId = entity.getImgID();
        stmt.bindLong(3, imgId);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();

        String userName = entity.getUsername();
        if (userName != null) {
            stmt.bindString(1, userName);
        }
        String slogan = entity.getSlogan();
        if (slogan != null) {
            stmt.bindString(2, slogan);
        }
        int imgId = entity.getImgID();
        stmt.bindLong(3, imgId);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // slogan
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // AreaName

        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setUsername(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSlogan(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImgID(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
    }
    
    @Override
    protected final String updateKeyAfterInsert(User entity, long rowId) {
        return entity.getUsername();
    }
    
    @Override
    public String getKey(User entity) {
        if(entity != null) {
            return entity.getUsername();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getUsername() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}